backend:
  name: github
  repo: jelle619/jellezwie.rs
  branch: master

public_folder: "characters"

collections:
  - name: "entry"
    label: "Entry"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Publish Date", name: "date", widget: "string"}
